version: "3.8"
services:
  db:
    image: postgres:latest

    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Dodobot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - customname

  bot:
    image: litpulla/dodobot
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - DefaultConnection=Host=db;Port=5432;Username=postgres;Password=postgres;Database=postgres
    networks:
      - customname
    volumes:
      - ~/.aspnet/https:/https:ro

networks:
  customname:

volumes:
  postgres_data:
    external: true
